name: Build OpenJDK 11 for Android

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_android:
    strategy:
      matrix:
        arch: [ "aarch32", "aarch64", "x86", "x86_64" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: set up JDK 10
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: Build with CI build script
      run: bash "ci_build_arch_${{matrix.arch}}.sh"
    - name: Upload JDK build output
      uses: actions/upload-artifact@v2
      with:
        name: "jdk11-${{matrix.arch}}"
        path: jdk11*.tar.xz

    - name: Setup tmate session if failed
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

    - name: Upload JRE build output
      uses: actions/upload-artifact@v2
      with:
        name: 'jre11-${{matrix.arch}}'
        path: jre11*.tar.xz
    - name: Upload JRE debuginfo build output
      uses: actions/upload-artifact@v2
      with:
        name: "jre11-debuginfo-${{matrix.arch}}"
        path: dizout

  fcl:
    needs: build_android
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get jre11-aarch32
      uses: actions/download-artifact@v2
      with:
        name: jre11-aarch32
        path: fcl
    - name: Get jre11-aarch64
      uses: actions/download-artifact@v2
      with:
        name: jre11-aarch64
        path: fcl
    - name: Get jre11-x86
      uses: actions/download-artifact@v2
      with:
        name: jre11-x86
        path: fcl
    - name: Get jre11-x86_64
      uses: actions/download-artifact@v2
      with:
        name: jre11-x86_64
        path: fcl
    - name: Repack JRE
      run: bash "repackjre.sh" $GITHUB_WORKSPACE/fcl $GITHUB_WORKSPACE/fcl/jre11-fcl
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: jre11-fcl
          path: fcl/jre11-fcl/*
